import {
  FileText,
  ImageIcon,
  Video,
  Music,
  Archive,
  FileImage,
  QrCode,
  Barcode,
  ImageDown,
  Scissors,
  Type,
  Hash,
  Code,
  Binary,
  Minimize,
} from "lucide-react"

export type ToolCategory = "all" | "file" | "image" | "text"

export interface Tool {
  id: string
  name: string
  description: string
  category: ToolCategory
  icon: any
  path: string
}

export const tools: Tool[] = [
  // File Conversion Tools
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF documents to editable Word files",
    category: "file",
    icon: FileText,
    path: "/tools/pdf-to-word",
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Word documents to PDF format",
    category: "file",
    icon: FileText,
    path: "/tools/word-to-pdf",
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert images to PDF documents",
    category: "file",
    icon: FileImage,
    path: "/tools/image-to-pdf",
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert PDF pages to image files",
    category: "file",
    icon: ImageIcon,
    path: "/tools/pdf-to-image",
  },
  {
    id: "video-to-mp3",
    name: "Video to MP3",
    description: "Extract audio from video files",
    category: "file",
    icon: Music,
    path: "/tools/video-to-mp3",
  },
  {
    id: "audio-to-text",
    name: "Audio to Text",
    description: "Convert speech to text transcription",
    category: "file",
    icon: Type,
    path: "/tools/audio-to-text",
  },
  {
    id: "zip-extractor",
    name: "ZIP Extractor",
    description: "Extract files from ZIP and RAR archives",
    category: "file",
    icon: Archive,
    path: "/tools/zip-extractor",
  },
  {
    id: "file-compressor",
    name: "File Compressor",
    description: "Compress PDF, images, and videos",
    category: "file",
    icon: Minimize,
    path: "/tools/file-compressor",
  },
  // Image & Media Tools
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to custom dimensions",
    category: "image",
    icon: ImageDown,
    path: "/tools/image-resizer",
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Reduce image file size without quality loss",
    category: "image",
    icon: Minimize,
    path: "/tools/image-compressor",
  },
  {
    id: "qr-generator",
    name: "QR Code Generator",
    description: "Create QR codes from text or URLs",
    category: "image",
    icon: QrCode,
    path: "/tools/qr-generator",
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate barcodes for products",
    category: "image",
    icon: Barcode,
    path: "/tools/barcode-generator",
  },
  {
    id: "image-to-text",
    name: "Image to Text (OCR)",
    description: "Extract text from images",
    category: "image",
    icon: Type,
    path: "/tools/image-to-text",
  },
  {
    id: "heic-to-jpg",
    name: "HEIC to JPG",
    description: "Convert HEIC images to JPG format",
    category: "image",
    icon: ImageIcon,
    path: "/tools/heic-to-jpg",
  },
  {
    id: "gif-maker",
    name: "GIF Maker",
    description: "Create animated GIFs from images",
    category: "image",
    icon: Video,
    path: "/tools/gif-maker",
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Crop and trim images",
    category: "image",
    icon: Scissors,
    path: "/tools/image-cropper",
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Extract colors from images",
    category: "image",
    icon: ImageIcon,
    path: "/tools/color-picker",
  },
  // Text & Developer Tools
  {
    id: "case-converter",
    name: "Text Case Converter",
    description: "Convert text to upper, lower, or sentence case",
    category: "text",
    icon: Type,
    path: "/tools/case-converter",
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words and characters in text",
    category: "text",
    icon: Hash,
    path: "/tools/word-counter",
  },
  {
    id: "line-break-remover",
    name: "Line Break Remover",
    description: "Remove unwanted line breaks from text",
    category: "text",
    icon: Scissors,
    path: "/tools/line-break-remover",
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format and beautify JSON data",
    category: "text",
    icon: Code,
    path: "/tools/json-formatter",
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    description: "Encode or decode Base64 strings",
    category: "text",
    icon: Binary,
    path: "/tools/base64-encoder",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256 hashes",
    category: "text",
    icon: Hash,
    path: "/tools/hash-generator",
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure random passwords",
    category: "text",
    icon: Hash,
    path: "/tools/password-generator",
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate unique identifiers",
    category: "text",
    icon: Hash,
    path: "/tools/uuid-generator",
  },
  {
    id: "text-diff",
    name: "Text Diff",
    description: "Compare two texts and find differences",
    category: "text",
    icon: Code,
    path: "/tools/text-diff",
  },
  {
    id: "code-beautifier",
    name: "Code Beautifier",
    description: "Format and beautify code",
    category: "text",
    icon: Code,
    path: "/tools/code-beautifier",
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text",
    category: "text",
    icon: Type,
    path: "/tools/lorem-ipsum",
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV data to JSON format",
    category: "text",
    icon: Code,
    path: "/tools/csv-to-json",
  },
]
